class ThrowException extends Exception
{
	public void limitChecking(double cgpa) throws ArithmeticException
	{
		if(cgpa < 0 || cgpa > 4)
		{
			throw new ArithmeticException("You have given an invalid cgpa") ;
		}
		else
		{
			System.out.println("Cgpa is "+cgpa) ;
		}
	}
	
	public static void main(String arg[])
	{
		try
		{
			ThrowException t = new ThrowException() ;
			t.limitChecking(7.0) ;
		}
		catch(Exception e)
		{
			System.out.println(e) ;
		}
	}

}

**********************************************************************************

import java.util.Scanner ;

public class ExceptionSample
{
	public static void main(String arg[])
	{
		/*int a ;
		
		System.out.println("Enter an integer value: ") ;
		Scanner sc = new Scanner(System.in) ;
		a = sc.nextInt() ;
		
		System.out.println("Value is "+a) ;
		*/
		try
		{
			int value1, value2 ;
			Scanner s = new Scanner(System.in) ;
			
			System.out.println("Enter a number:") ;
			value1 = s.nextInt() ;
			
			System.out.println("Enter a number:") ;
			value2 = s.nextInt() ;
			
			int result = value1 / value2 ;
			System.out.println("Result is "+result) ;
		}
		catch(Exception e)
		{
			System.out.println("Divided by 0 is not possible") ;
			
		}
		
		
		
	}
}